### ISSUE TITLE
Not work in Views 7.x-3.6

### ISSUE THREAD

**Issue by PVasili** [drupol/views_extra_operator#1]
1) Warning: Deprecated function: Call-time pass-by-reference has been deprecated in function module_load_include() (string 331 in file /home/.../includes/module.inc).
2) Any operator in argument: HTTP code 500 :(

**Comment by drupol** [comment]
Hi,

I don't have time for this module right now, pull requests are welcome.

Thanks !

**Comment by PVasili** [comment]
Hi. Have you  some time to check this module? 
In the new version Views it  causes WSOD :(

**Comment by drupol** [comment]
Hello,

No, I don't use this module anymore and I don't have time to put into it right now.
Pull requests are welcome of course.
